CC = gcc

day1.1: 
	$(CC) adventofcode-01.1.c -o ./bin/adventofcode-01.1 -W -Wall && ./bin/adventofcode-01.1
	
day1.2: 
	$(CC) adventofcode-01.2.c -o ./bin/adventofcode-01.2 -W -Wall && ./bin/adventofcode-01.2
