CC = gcc

day1.1: 
	$(CC) adventofcode-01.1.c -o ./bin/adventofcode-01.1 -W -Wall
	./bin/adventofcode-01.1
	
day1.2: 
	$(CC) adventofcode-01.2.c -o ./bin/adventofcode-01.2 -W -Wall
	./bin/adventofcode-01.2

day2.1: 
	$(CC) adventofcode-02.1.c -o ./bin/adventofcode-02.1 -W -Wall
	./bin/adventofcode-02.1
	
day2.2: 
	$(CC) adventofcode-02.2.c -o ./bin/adventofcode-02.2 -W -Wall
	./bin/adventofcode-02.2
	
day3.1: 
	$(CC) adventofcode-03.1.c -o ./bin/adventofcode-03.1 -W -Wall
	./bin/adventofcode-03.1
	
day3.2: 
	$(CC) adventofcode-03.2.c -o ./bin/adventofcode-03.2 -W -Wall
	./bin/adventofcode-03.2
